# Nome do Workflow
name: CI/CD - Build e Testes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # Define o diretório de trabalho padrão para todos os passos deste job
    defaults:
      run:
        working-directory: ./ClassAI # <-- PASSO CHAVE: Diz para todos os comandos rodarem dentro da pasta ClassAI

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          # O cache também precisa saber onde está o package-lock.json
          cache-dependency-path: ClassAI/package-lock.json

      - name: Instalar dependências
        run: npm ci

      - name: Rodar os testes
        run: npm test
